version: '3'
services:

  loadtests:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /src
    command: init.sh
    volumes:
      - .:/src
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
